### PR TITLE
Alternate faces

### LINKED ISSUE #10: Properly support alternating font face tags like .BR and .RB
Currently, `.BR` tags are treated as lists of manpage links, which are rendered in boldface, connected by commas. This is frequently how this tag is used, but it is not actually what it means, and there are a series of other tags with similar meanings that could be supported, too.

The meaning of `.BR` is, [according to `groff(7)`](https://manpages.debian.org/jessie/groff/groff_man.7.en.html), "Causes text on the same line to appear alternately in bold face and roman." This means that a line like:

    .BR a b c d

Should be rendered as "**a** b **c** d". Similarly, `.RB` is alternate roman and bold face, so the same line would be "a **b** c **d**". There are also tags for alternating italic and roman (`.RI`, `.IR`), and bold and italic (`.BI`, `.IB`).

Once this is implemented, I think the `linkfile` subroutine will be able to sufficiently check for links if necessary, so that part can be stripped from the existing `.BR` handler.

### PR DESCRIPTION
**Pull request by dmiller-nmap**
Fixes #10

### CODE REVIEW

**Comment by bagder** [comment]
conflicts!

**Comment by dmiller-nmap** [comment]
Ok, I think this looks good now. Please let me know if you have concerns.

**Comment by bagder** [comment]
Heh, sorry but I assume that when I merged your other PR this conflicts again...

**Comment by dmiller-nmap** [comment]
Yeah, sorry. It's hard to submit PRs that each depend on the previous one being committed. This is the last one, though.

**Comment by bagder** [comment]
this still says it can't be rebased!

**Comment by dmiller-nmap** [comment]
@bagder I don't understand why. Github says there are no conflicts, and I was able to do a fast-forward merge with master. Do you have local changes to master that you haven't pushed to Github yet? If all else fails, I can try doing a brand new clean PR.

**Comment by dmiller-nmap** [comment]
I'm closing this PR in favor of #19 . Please review that PR instead, thank you.

**Pull request closed without merging**
